http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ifxquerytrn'
serviceEndpoints:
  httpbin:
    url: 'http://10.100.44.82:5000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: getting-start
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
     - key-auth:
     - proxy:
          - action:
              serviceEndpoint: httpbin 

